[package]
name = "wrongsv-vless-encoding"
version.workspace = true
edition.workspace = true

[dependencies]
wrongsv-protocol.workspace = true
wrongsv-net-types.workspace = true
prost.workspace = true
bytes.workspace = true
thiserror.workspace = true

[dev-dependencies]
wrongsv-uuid.workspace = true

[build-dependencies]
prost-build = "0.14"
