[package]
name = "wrongsv-anytls"
version.workspace = true
edition.workspace = true

[dependencies]
rustls = { version = "0.23", default-features = false, features = ["std", "aws_lc_rs", "tls12"] }
rcgen = "0.13"
sha2.workspace = true
rand.workspace = true
thiserror.workspace = true
tracing.workspace = true
md-5.workspace = true
wrongsv-net-types.workspace = true
