[package]
name = "wrongsv-server"
version.workspace = true
edition.workspace = true

[dependencies]
wrongsv-protocol.workspace = true
wrongsv-vless.workspace = true
wrongsv-vless-encoding.workspace = true
wrongsv-encryption.workspace = true
wrongsv-kyber.workspace = true
wrongsv-reality.workspace = true
wrongsv-anytls.workspace = true
wrongsv-shadowsocks.workspace = true
wrongsv-websocket.workspace = true
wrongsv-grpc.workspace = true
rustls = { version = "0.23", default-features = false, features = ["tls12", "std", "aws_lc_rs"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "net", "sync", "macros", "time"] }
h2 = "0.4"
http = "1"
h3 = "0.0.8"
h3-quinn = "0.0.10"
quinn = "0.11.9"
kcp = "0.6"
rustls-pemfile = "2"
wrongsv-net-types.workspace = true
wrongsv-uuid.workspace = true
bytes.workspace = true
base64.workspace = true
serde.workspace = true
toml.workspace = true
thiserror.workspace = true
sha2.workspace = true
tracing.workspace = true
ctrlc.workspace = true
